// Generated by CoffeeScript 2.7.0
(function() {
  var clearOutputButton, conjunctionColorPickerElement, conjunctionToRemove, conjunctionsList, conjunctionsListElement, darkMode, highlightCode, insertConjunction, insertKeyword, insertLiteral, insertOther, keywordColorPickerElement, keywordToRemove, keywordsList, keywordsListElement, lex, literalColorPickerElement, loadButton, loadData, newTextArea, registerConjunction, registerKeyword, registerNewConjunctionButton, registerNewKeywordButton, removeConjunction, removeConjunctionButton, removeKeyword, removeKeywordButton, saveButton, saveData, submitCodeButton, toggleDarkMode, toggleDarkModeElement,
    indexOf = [].indexOf;

  keywordColorPickerElement = document.getElementById('keyword-color-picker');

  literalColorPickerElement = document.getElementById('literal-color-picker');

  conjunctionColorPickerElement = document.getElementById('conjunction-color-picker');

  newTextArea = document.getElementById('highlighted-text');

  submitCodeButton = document.getElementById('submit-main-input');

  registerNewKeywordButton = document.getElementById('submit-new-keyword-button');

  registerNewConjunctionButton = document.getElementById('submit-new-conjunction-button');

  keywordsListElement = document.getElementById('keywords-list');

  conjunctionsListElement = document.getElementById('conjunctions-list');

  clearOutputButton = document.getElementById('clear-highlighted-text');

  removeKeywordButton = document.getElementById('submit-remove-keyword-button');

  keywordToRemove = document.getElementById('remove-keyword');

  removeConjunctionButton = document.getElementById('submit-remove-conjunction-button');

  conjunctionToRemove = document.getElementById('remove-conjunction-textbox');

  saveButton = document.getElementById('save-registry');

  loadButton = document.getElementById('load-registry');

  toggleDarkModeElement = document.getElementById('toggle-dark-mode');

  keywordsList = [];

  conjunctionsList = [];

  darkMode = false;

  lex = function(word) {
    if (indexOf.call(keywordsList, word) >= 0) {
      return 'keyword';
    }
    if (indexOf.call(conjunctionsList, word) >= 0) {
      return 'conjunction';
    }
    if (word.match([/a-zA-Z0-9/])) {
      return 'literal'; // refactor to support strings
    }
    return 'other';
  };

  insertKeyword = function(keyword) {
    var keywordColor;
    keywordColor = keywordColorPickerElement.value;
    newTextArea.innerHTML += `<span style='color: ${keywordColor}'>${keyword}</span> `;
    console.log('added new keyword');
  };

  insertLiteral = function(literal) {
    var literalColor;
    literalColor = literalColorPickerElement.value;
    newTextArea.innerHTML += `<span style='color: ${literalColor}'>${literal}</span> `;
    console.log('added new literal');
  };

  insertConjunction = function(conjunction) {
    var conjunctionColor;
    conjunctionColor = conjunctionColorPickerElement.value;
    newTextArea.innerHTML += `<span style='color: ${conjunctionColor}'>${conjunction}</span> `;
    console.log('added new conjunction');
  };

  insertOther = function(word) {
    console.log('dark mode is:');
    console.log(darkMode);
    if (darkMode === true) {
      newTextArea.innerHTML += `<span style='color: white'>${word}</span> `;
      return;
    } else {
      newTextArea.innerHTML += `${word} `;
      console.log('added new word');
    }
  };

  // basically the main function
  highlightCode = function() {
    var code, i, len, results, token, word, words;
    code = document.getElementById('main-input-text').value;
    if (code.length === 0) {
      console.log('nothing to highlight');
      return;
    }
    if (keywordsList.length === 0 && conjunctionsList.length === 0) {
      alert("You have no registered keywords or conjunctions; nothing will be highlighted.");
      return;
    }
    words = code.replace(/\n/g, ' NEWLINE ').split(/\s+/);
    results = [];
    for (i = 0, len = words.length; i < len; i++) {
      word = words[i];
      console.log(word);
      token = lex(word);
      if (word === 'NEWLINE') {
        newTextArea.innerHTML += '<br>';
        continue;
      }
      if (token === 'keyword') {
        insertKeyword(word);
      }
      if (token === 'literal') {
        insertLiteral(word);
      }
      if (token === 'conjunction') {
        insertConjunction(word);
      }
      if (token === 'other') {
        results.push(insertOther(word));
      } else {
        results.push(void 0);
      }
    }
    return results;
  };

  registerKeyword = function() {
    var newKeyword;
    newKeyword = document.getElementById('add-keyword').value;
    if (newKeyword.length === 0) {
      alert("The textbox is empty");
      return;
    }
    if (indexOf.call(keywordsList, newKeyword) >= 0) {
      alert(`This keyword is already registered: ${newKeyword}`);
      return;
    }
    keywordsList.push(newKeyword);
    return keywordsListElement.innerHTML += `<li>${newKeyword}</li>`;
  };

  registerConjunction = function() {
    var newConjunction;
    newConjunction = document.getElementById('add-conjunction').value;
    if (newConjunction.length === 0) {
      alert("The textbox is empty");
      return;
    }
    if (indexOf.call(conjunctionsList, newConjunction) >= 0) {
      alert(`This conjunction is already registered: ${newConjunction}`);
      return;
    }
    conjunctionsList.push(newConjunction);
    return conjunctionsListElement.innerHTML += `<li>${newConjunction}</li>`;
  };

  removeKeyword = function() {
    var i, j, keywordIterator, keywords, len, len1, ref, results;
    if (ref = keywordToRemove.value, indexOf.call(keywordsList, ref) < 0) {
      alert(`The keyword ${keywordToRemove.value} is not registered.`);
      return;
    }
    for (i = 0, len = keywordsList.length; i < len; i++) {
      keywordIterator = keywordsList[i];
      if (keywordIterator === keywordToRemove.value) {
        keywordsList.splice(keywordsList.indexOf(keywordIterator), 1);
      }
    }
    keywords = Array.from(keywordsListElement.getElementsByTagName('li'));
    results = [];
    for (j = 0, len1 = keywords.length; j < len1; j++) {
      keywordIterator = keywords[j];
      if (keywordIterator.innerHTML === keywordToRemove.value) {
        results.push(keywordsListElement.removeChild(keywordIterator));
      } else {
        results.push(void 0);
      }
    }
    return results;
  };

  removeConjunction = function() {
    var conjunctionIterator, conjunctions, i, j, len, len1, ref, results;
    if (ref = conjunctionToRemove.value, indexOf.call(conjunctionsList, ref) < 0) {
      alert(`The conjunction ${conjunctionToRemove.value} is not registered.`);
      return;
    }
    console.log('fired removeConjunction');
    for (i = 0, len = conjunctionsList.length; i < len; i++) {
      conjunctionIterator = conjunctionsList[i];
      if (conjunctionIterator === conjunctionToRemove.value) {
        conjunctionsList.splice(conjunctionsList.indexOf(conjunctionIterator), 1);
        console.log('removed conjunction from list');
      }
    }
    conjunctions = Array.from(conjunctionsListElement.getElementsByTagName('li'));
    results = [];
    for (j = 0, len1 = conjunctions.length; j < len1; j++) {
      conjunctionIterator = conjunctions[j];
      if (conjunctionIterator.innerHTML === conjunctionToRemove.value) {
        conjunctionsListElement.removeChild(conjunctionIterator);
        results.push(console.log('removed conjunction from html'));
      } else {
        results.push(void 0);
      }
    }
    return results;
  };

  saveData = function() {
    var data;
    data = {
      keywords: keywordsList,
      conjunctions: conjunctionsList
    };
    localStorage.setItem('data', JSON.stringify(data));
    return console.log('saved data');
  };

  loadData = function() {
    var conjunction, data, i, j, keyword, len, len1;
    data = JSON.parse(localStorage.getItem('data'));
    keywordsList = data.keywords;
    conjunctionsList = data.conjunctions;
    for (i = 0, len = keywordsList.length; i < len; i++) {
      keyword = keywordsList[i];
      keywordsListElement.innerHTML += `<li>${keyword}</li>`;
    }
    for (j = 0, len1 = conjunctionsList.length; j < len1; j++) {
      conjunction = conjunctionsList[j];
      conjunctionsListElement.innerHTML += `<li>${conjunction}</li>`;
    }
    return console.log('loaded data');
  };

  toggleDarkMode = function() {
    if (darkMode === false) {
      newTextArea.style.backgroundColor = "#191a1c";
      darkMode = true;
      return console.log('dark mode is on');
    } else {
      newTextArea.style.backgroundColor = "white";
      darkMode = false;
      return console.log('dark mode is off');
    }
  };

  submitCodeButton.addEventListener('click', function() {
    console.log('clicked');
    return highlightCode();
  });

  registerNewKeywordButton.addEventListener('click', function() {
    return registerKeyword();
  });

  registerNewConjunctionButton.addEventListener('click', function() {
    return registerConjunction();
  });

  clearOutputButton.addEventListener('click', function() {
    return newTextArea.innerHTML = '';
  });

  removeKeywordButton.addEventListener('click', function() {
    return removeKeyword();
  });

  removeConjunctionButton.addEventListener('click', function() {
    return removeConjunction();
  });

  saveButton.addEventListener('click', function() {
    return saveData();
  });

  loadButton.addEventListener('click', function() {
    return loadData();
  });

  toggleDarkModeElement.addEventListener('click', function() {
    return toggleDarkMode();
  });

}).call(this);

//# sourceMappingURL=index.js.map
