// Generated by CoffeeScript 2.7.0
(function() {
  var clearOutputButton, conjunctionColor, conjunctionColorPickerElement, conjunctionsList, conjunctionsListElement, highlightCode, insertConjunction, insertKeyword, insertLiteral, insertOther, keywordColor, keywordColorPickerElement, keywordsList, keywordsListElement, lex, literalColor, literalColorPickerElement, newTextArea, registerConjunction, registerKeyword, registerNewConjunctionButton, registerNewKeywordButton, submitCodeButton,
    indexOf = [].indexOf;

  keywordColorPickerElement = document.getElementById('keyword-color-picker');

  literalColorPickerElement = document.getElementById('literal-color-picker');

  conjunctionColorPickerElement = document.getElementById('conjunction-color-picker');

  keywordColor = keywordColorPickerElement.value;

  literalColor = literalColorPickerElement.value;

  conjunctionColor = conjunctionColorPickerElement.value;

  newTextArea = document.getElementById('highlighted-text');

  submitCodeButton = document.getElementById('submit-main-input');

  registerNewKeywordButton = document.getElementById('submit-new-keyword-button');

  registerNewConjunctionButton = document.getElementById('submit-new-conjunction-button');

  keywordsListElement = document.getElementById('keywords-list');

  conjunctionsListElement = document.getElementById('conjunctions-list');

  clearOutputButton = document.getElementById('clear-highlighted-text');

  keywordsList = [];

  conjunctionsList = [];

  lex = function(word) {
    if (indexOf.call(keywordsList, word) >= 0) {
      return 'keyword';
    }
    if (indexOf.call(conjunctionsList, word) >= 0) {
      return 'conjunction';
    }
    if (word.match([/a-zA-Z0-9/])) {
      return 'literal'; // refactor to support strings
    }
    return 'other';
  };

  insertKeyword = function(keyword) {
    newTextArea.innerHTML += `<span style='color: ${keywordColor}'>${keyword}</span> `;
    console.log('added new keyword');
  };

  insertLiteral = function(literal) {
    newTextArea.innerHTML += `<span style='color: ${literalColor}'>${literal}</span> `;
    return console.log('added new literal');
  };

  insertConjunction = function(conjunction) {
    newTextArea.innerHTML += `<span style='color: ${conjunctionColor}'>${conjunction}</span> `;
    return console.log('added new conjunction');
  };

  insertOther = function(word) {
    newTextArea.innerHTML += `${word} `;
    return console.log('added new word');
  };

  // basically the main function
  highlightCode = function() {
    var code, i, len, results, token, word, words;
    code = document.getElementById('main-input-text').value;
    if (code.length === 0) {
      console.log('nothing to highlight');
      return;
    }
    if (keywordsList.length === 0 && conjunctionsList.length === 0) {
      alert("You have no registered keywords or conjunctions; nothing will be highlighted.");
      return;
    }
    words = code.replace(/\n/g, ' NEWLINE ').split(/\s+/);
    results = [];
    for (i = 0, len = words.length; i < len; i++) {
      word = words[i];
      console.log(word);
      token = lex(word);
      if (word === 'NEWLINE') {
        newTextArea.innerHTML += '<br>';
        continue;
      }
      if (token === 'keyword') {
        insertKeyword(word);
      }
      if (token === 'literal') {
        insertLiteral(word);
      }
      if (token === 'conjunction') {
        insertConjunction(word);
      }
      if (token === 'other') {
        results.push(insertOther(word));
      } else {
        results.push(void 0);
      }
    }
    return results;
  };

  registerKeyword = function() {
    var newKeyword;
    newKeyword = document.getElementById('add-keyword').value;
    if (newKeyword.length === 0) {
      alert("The textbox is empty");
      return;
    }
    if (indexOf.call(keywordsList, newKeyword) >= 0) {
      alert(`This keyword is already registered: ${newKeyword}`);
      return;
    }
    keywordsList.push(newKeyword);
    return keywordsListElement.innerHTML += `<li>${newKeyword}</li>`;
  };

  registerConjunction = function() {
    var newConjunction;
    newConjunction = document.getElementById('add-conjunction').value;
    if (newConjunction.length === 0) {
      alert("The textbox is empty");
      return;
    }
    if (indexOf.call(conjunctionsList, newConjunction) >= 0) {
      alert(`This conjunction is already registered: ${newConjunction}`);
      return;
    }
    conjunctionsList.push(newConjunction);
    return conjunctionsListElement.innerHTML += `<li>${newConjunction}</li>`;
  };

  submitCodeButton.addEventListener('click', function() {
    console.log('clicked');
    return highlightCode();
  });

  registerNewKeywordButton.addEventListener('click', function() {
    return registerKeyword();
  });

  registerNewConjunctionButton.addEventListener('click', function() {
    return registerConjunction();
  });

  clearOutputButton.addEventListener('click', function() {
    return newTextArea.innerHTML = '';
  });

}).call(this);

//# sourceMappingURL=index.js.map
